#!/usr/bin/env bash
# shellcheck disable=SC1091

set -euo pipefail
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
. 'script/utils.sh'
. 'script/import_python.sh'

pushd src

pipenv run python fetch_html.py
pipenv run python download_images.py
pipenv run python app.py
