#!/usr/bin/env bash
# shellcheck disable=SC1091

set -euo pipefail
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
. 'script/utils.sh'
. 'script/import_python.sh'

pushd 'static_site/www.bucketheadpikes.com'
ls *.html > ../../html_pages.txt
